#!/usr/bin/env python3
"""The PEG authoring formats — the surface a teacher actually writes in.

THE THIRD DECLARATION, and the one closest to the intake program's real output.
`shape_inventory` says what blocks exist, `grader_inputs` says what scores what,
`structure_kids` says what holds what — all three describe OLX. But OLX is not
what a teacher writes. lo-blocks ships **PEG content formats**: compact,
plain-text syntaxes that parse into blocks, one file per exercise. A
`.textSelectionpeg` is prose with the answers in brackets:

    Look at each scenario below and highlight the examples that show [reinforcement].
    1. [A child receives a sticker for completing homework on time].

**An intake program that emits OLX where a PEG format would do has produced
something the teacher cannot edit afterwards.** That is the whole reason this
pass exists: the question "how does a teacher author an item without writing
XML" already has an answer in this engine, and it was built for exactly the
materials the intake program will be reading.

UNLIKE THE OTHER TWO, THIS ONE IS DECLARED. `packages/shared/generated/
parserRegistry.ts` maps every extension to its grammar, its directory, a display
name and a `creatable` flag saying whether a teacher may author one. So this
module READS that registry rather than declaring a mapping of its own, and what
it declares instead is the part the registry does not carry: what the teacher
writes, and how the file is reached from a course.

A SIXTH REFERENCE MECHANISM. The five already recorded relate blocks to blocks.
This one relates a block to a FILE: `<Chat src="psych_sba_part2.chatpeg"
cast="characters.cast" />`. A course's peg content is reached by `src=`, is
absent from `manifest.yaml`, and is invisible to every block-level scan.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

SCHEMA_VERSION = 1

# What the teacher writes, per format. The registry gives the mapping; this gives
# the shape of the source, which is what an intake program has to produce.
AUTHORED_AS: dict[str, str] = {
    "textSelectionpeg": "prose with the answers in [square brackets]",
    "matchingpeg": "two columns joined by a separator, one pair per line",
    "sortpeg": "items in their correct order, one per line",
    "dropdownpeg": "options in a list, the key marked",
    "chatpeg": "a dialogue script: `::id [attrs]` turn markers and speech",
    "idlistpeg": "a list of OLX ids, one per line -- an item bank",
    "capapeg": "an Open edX-style markdown problem",
    "clippeg": "a range notation for selecting part of another file",
    "dndpeg": "drag-and-drop image labelling (prototype)",
    "demopeg": "arithmetic, for grammar development",
    "grammarpeg": "a calculation grammar -- engine internals, not content",
    "exprpeg": "a state-language expression -- engine internals",
    "templatepeg": "a {{placeholder}} template -- engine internals",
}

# Extensions found in course content that the engine does not register. Declared
# so that "unknown format" is a decision rather than a silent skip.
UNREGISTERED = {
    "textHighlightpeg":
        "DEAD. Three files in the psych course use it and lo-blocks registers it "
        "NOWHERE. Each is BYTE-IDENTICAL to a `.textSelectionpeg` beside it, so "
        "this is a renamed grammar whose old files were left behind. Nothing "
        "references either copy, and the manifest routes neither.",
}

# Authored content no `src=` reaches, named with the reason. Declared rather
# than tolerated: a NEW orphan must fail, and these six must not hide it.
ORPHANED_CONTENT = {
    "psych_reinforce_punish.textSelectionpeg": "psych highlighting quiz, unrouted",
    "psych_positive_negative.textSelectionpeg": "psych highlighting quiz, unrouted",
    "psych_bedtime_strategies.textSelectionpeg": "psych highlighting quiz, unrouted",
    "psych_reinforce_punish.textHighlightpeg": "byte-identical dead twin of the above",
    "psych_positive_negative.textHighlightpeg": "byte-identical dead twin",
    "psych_bedtime_strategies.textHighlightpeg": "byte-identical dead twin",
}

_INFO = re.compile(r"'(\w+)':\s*\{\s*grammarName:\s*'(\w+)',\s*grammarDir:\s*'([^']+)'")
_META = re.compile(r"'(\w+)':\s*\{\s*name:\s*\"([^\"]+)\",\s*creatable:\s*(true|false)")
_SRC = re.compile(r'\b(?:src|cast)\s*=\s*"([^"]+)"')


def registry(lo: str) -> dict:
    """The engine's own PEG registry. Generated, committed, authoritative."""
    path = os.path.join(lo, "packages", "shared", "generated", "parserRegistry.ts")
    if not os.path.exists(path):
        raise SystemExit(
            f"peg_formats: no parser registry at {path}. It is generated by "
            f"`npm run build:parser-registry`. Guessing the format list from file "
            f"extensions found in courses would have declared `textHighlightpeg` "
            f"a real format -- it is not registered anywhere.")
    text = open(path).read()
    info = {ext: {"grammar": g, "dir": d} for ext, g, d in _INFO.findall(text)}
    for ext, name, creatable in _META.findall(text):
        info.setdefault(ext, {})["display"] = name
        info[ext]["creatable"] = creatable == "true"
    return info


def course_files(roots: list[str]) -> dict[str, list[str]]:
    """Every peg-ish content file in the courses, by extension."""
    import olx_corpus

    out: dict[str, list[str]] = {}
    for root in roots:
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = [d for d in dirnames if d not in olx_corpus.ARTIFACT_DIRS]
            for fn in filenames:
                ext = fn.rsplit(".", 1)[-1] if "." in fn else ""
                if ext.endswith("peg") or ext in ("cast", "liquid"):
                    out.setdefault(ext, []).append(
                        os.path.relpath(os.path.join(dirpath, fn), root))
    return {k: sorted(v) for k, v in sorted(out.items())}


def referenced_files(roots: list[str]) -> set[str]:
    """Filenames named by a `src=` or `cast=` anywhere in the OLX."""
    import olx_corpus

    seen = set()
    for _label, text in olx_corpus.texts(roots):
        for val in _SRC.findall(text):
            seen.add(os.path.basename(val))
    return seen


def verify(reg: dict, found: dict, referenced: set,
           course_only: dict | None = None) -> list[str]:
    out = []
    for ext in sorted(reg):
        if ext not in AUTHORED_AS:
            out.append(f"{ext} is a registered PEG format and AUTHORED_AS does not "
                       f"say what a teacher writes in it -- which is the one thing "
                       f"an intake program needs from this table")
    for ext in sorted(AUTHORED_AS):
        if ext not in reg:
            out.append(f"AUTHORED_AS describes {ext}, which the engine's registry "
                       f"does not know")
    for ext, files in sorted(found.items()):
        if ext in ("cast", "liquid"):
            continue
        if ext not in reg and ext not in UNREGISTERED:
            out.append(f".{ext} is used by {len(files)} course file(s) "
                       f"({files[0]}) and is registered by NO grammar -- say what "
                       f"it is, or it is content nothing can parse")
    for ext in sorted(UNREGISTERED):
        if ext in reg:
            out.append(f"{ext} is declared unregistered but the engine registers "
                       f"it now -- the declaration has outlived its reason")
        if ext not in found:
            out.append(f"{ext} is declared unregistered and no course uses it any "
                       f"more -- drop the entry")
    # GRAMMAR SIDECARS ARE NOT COURSE CONTENT. Each grammar ships
    # `<name>.pegjs.template.<ext>` and `<name>.pegjs.preview.<ext>` -- the
    # starter text and the doc preview the Studio offers an author. They are
    # loaded by the grammar tooling, never by a `src=`, and counting them as
    # orphaned content buried the six real orphans among twenty-six.
    # ORPHANS ARE A COURSE QUESTION, NOT AN ENGINE ONE. The engine carries
    # `test-*.capapeg` fixtures and demo scripts that no course OLX names, and
    # that is what they are for. An unreferenced file in a COURSE is different:
    # it is authored teaching content that nothing loads.
    pool = course_only if course_only is not None else found
    orphans = [f for ext, files in pool.items() if ext.endswith("peg")
               for f in files
               if os.path.basename(f) not in referenced
               and ".pegjs.template." not in f and ".pegjs.preview." not in f
               and os.path.basename(f) not in ORPHANED_CONTENT]
    if orphans:
        out.append(f"{len(orphans)} peg content file(s) are authored content that "
                   f"no `src=` reaches: "
                   f"{', '.join(sorted(os.path.basename(o) for o in orphans)[:8])}"
                   f"{' ...' if len(orphans) > 8 else ''}")
    live = {f for ext, files in (course_only or found).items() for f in files}
    live = {os.path.basename(f) for f in live}
    for name in sorted(ORPHANED_CONTENT):
        if name not in live:
            out.append(f"{name} is declared orphaned content and is no longer "
                       f"present -- drop the entry rather than leaving a "
                       f"declaration about a file that is gone")
        elif name in referenced:
            out.append(f"{name} is declared orphaned and something now references "
                       f"it -- the declaration has outlived its reason")
    return out


def main(argv=None) -> int:
    import olx_corpus
    import paths

    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--lo-blocks", default=str(paths.LO))
    ap.add_argument("--json", metavar="PATH")
    args = ap.parse_args(argv)

    reg = registry(args.lo_blocks)
    roots = olx_corpus.default_roots()
    found = course_files(roots)
    referenced = referenced_files(roots)
    lo = os.path.abspath(args.lo_blocks)
    course_roots = [r for r in roots if os.path.abspath(r) != lo]
    course_only = course_files(course_roots)
    creatable = sorted(e for e, v in reg.items() if v.get("creatable"))

    print(f"  {len(reg)} PEG formats registered, {len(creatable)} creatable by an "
          f"author")
    for ext in creatable:
        n = len(found.get(ext, []))
        print(f"    {ext:<20} {reg[ext].get('display',''):<20} "
              f"{n if n else '-':>3} file(s) in the courses")
    other = sorted(e for e in reg if e not in creatable)
    print(f"  not author-creatable ({len(other)}): {', '.join(other)}")
    unused = [e for e in creatable if not found.get(e)]
    print(f"  creatable but used by NO course ({len(unused)}): "
          f"{', '.join(unused) or 'none'}")
    print(f"  {len(ORPHANED_CONTENT)} authored file(s) declared orphaned "
          f"(3 unrouted quizzes + 3 dead twins in an unregistered extension)")

    bad = verify(reg, found, referenced, course_only)
    if args.json:
        json.dump({"schema_version": SCHEMA_VERSION, "registry": reg,
                   "authored_as": AUTHORED_AS, "unregistered": UNREGISTERED,
                   "course_files": found}, open(args.json, "w"), indent=1)
        print(f"  written: {args.json}")
    if bad:
        print(f"\n  {len(bad)} FINDING(S):")
        for b in bad:
            print(f"    {b}")
        return 1
    print("  the PEG declaration agrees with the engine's registry and the courses.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
